/* loup_sequence.js — LOUP (Lube Oil Up-gradation Unit) DCS procedural-automation sequences.
   STARTUP is transcribed faithfully from the plant's DCS auto-sequence sheet (117 steps,
   5 controllers). SHUTDOWN is derived from standard hydroprocessing practice + the LOUP SOP
   Book (clearly marked DERIVED). Consumed by loup_autopilot.js.

   Step types drive the live engine:
     check   — logic verifies a condition (auto)
     field   — a Field Officer physical action (needs field confirm)
     signoff — operator must press a confirmation/START button (needs DCS sign-off)
     ramp    — a controller ramps a tag toward a target at a rate (animated)
     hold    — a hold timer runs (countdown)
     branch  — conditional: if PV meets criterion proceed, else the sequence goes on HOLD
   Optional: tag/target/rate/rateUnit/holdMin/cond for the engine + realism.
*/
const LOUP = {
  unit: "LOUP — Lube Oil Up-gradation Unit · Hydrotreater + Dewaxing",
  provenance: "⚠ ALL NUMERIC VALUES (pressures, temperatures, flows, setpoints, trip thresholds, hold values) HAVE BEEN RANDOMISED FOR CONFIDENTIALITY — they are representative/illustrative only and are NOT actual plant data. Procedure structure follows the LOUP start-up auto-sequence and the SOP Book 6000-series emergency procedures; execution runs entirely on a synthetic twin with no connection to any live DCS.",

  STARTUP: [
   {ctrl:1, title:"HP Circuit Pressurization & Hold Test", steps:[
     {n:1, grp:"STEP 1", by:"Field", type:"field", text:"Leak check done at 5.5 kg/cm²g with N₂ before starting"},
     {n:2, grp:"STEP 1", by:"Field/DCS", type:"field", text:"Make-up H₂ (112) lined up from B/L to PDS compressor discharge via UV-2701 & FV-2702"},
     {n:3, grp:"STEP 1", by:"Field/DCS", type:"field", text:"Stroke check done of FIC-2702"},
     {n:4, grp:"STEP 1", by:"Field/DCS", type:"field", text:"HP and LP segregated"},
     {n:5, grp:"STEP 1", by:"DCS", type:"signoff", text:"Press START SEQ — button turns GREEN. Confirm SEQ HEALTHYNESS button GREEN"},
     {n:6, grp:"STEP 1", by:"DCS", type:"signoff", text:"Press HP Circuit Pressurization & Hold Test — confirm colour GREEN"},
     {n:7, grp:"STEP 1", by:"DCS", type:"check", text:"IS-04 auto-reset by logic — confirm IS-04 healthy"},
     {n:8, grp:"STEP 1", by:"DCS", type:"check", text:"HS-2701 auto-reset by logic — confirm UV-2701 opened"},
     {n:9, grp:"STEP 2", by:"DCS", type:"ramp", text:"Ramping starts: 5.7 kg/hr up to 9.1 kg. 173PIC2502→AUTO 0% OP (SP=PV); 173FIC2702→CAS 0% OP. Confirm RAMPING START button GREEN",
      tag:"PIC2502", from:5.5, target:9.1, rate:4.5, rateUnit:"kg/hr"},
     {n:10, grp:"STEP 2", by:"DCS", type:"check", text:"Pressure ramps to 9.1 kg/cm²g — logic check PIC2502 ≥ 9.1, stop ramping"},
     {n:11, grp:"STEP 3", by:"DCS", type:"check", text:"173FIC2702→MAN 0% OP; logic confirms close feedback of FIC2702"},
     {n:12, grp:"STEP 4", by:"DCS", type:"hold", text:"System Hold Timer of 30 min starts", holdMin:30},
     {n:13, grp:"STEP 5", by:"DCS", type:"branch", text:"After 30 min, logic checks PIC2502 > 8.6 kg/cm²g. If Yes → STEP 6; If No → HOLD",
      tag:"PIC2502", cond:">8.6"},
     {n:14, grp:"STEP 5", by:"DCS/Field", type:"field", hr:true, text:"If on HOLD: leak-check and attend. To restart: STOP SEQ → RESET SEQ → START SEQ"},
     {n:15, grp:"STEP 6&7", by:"DCS", type:"check", text:"If hold test OK, STEP 6 starts"},
     {n:16, grp:"STEP 6&7", by:"DCS", type:"ramp", text:"Ramping 5.7 kg/hr from 9.1 to 18.2 kg/cm²g. 173PIC2502→AUTO; 173FIC2702→CAS",
      tag:"PIC2502", from:9.1, target:18.2, rate:4.5, rateUnit:"kg/hr"},
     {n:17, grp:"STEP 8", by:"DCS", type:"check", text:"173FIC2702→MAN 0% OP; confirm close feedback"},
     {n:18, grp:"STEP 9", by:"DCS", type:"hold", text:"System Hold Timer of 30 min starts", holdMin:30},
     {n:19, grp:"STEP 10", by:"DCS", type:"branch", text:"After 30 min, check PIC2502 > 17.7. If Yes → STEP 11; If No → HOLD",
      tag:"PIC2502", cond:">17.7"},
     {n:20, grp:"STEP 11&12&13", by:"DCS", type:"ramp", text:"Ramping 5.7 kg/hr from 18.2 to 21.2 kg/cm²g (final hold test)",
      tag:"PIC2502", from:18.2, target:21.2, rate:4.5, rateUnit:"kg/hr"},
     {n:21, grp:"STEP 14", by:"DCS", type:"check", text:"Logic resets IS-09A/B automatically"},
     {n:22, grp:"STEP 14", by:"DCS/Field", type:"field", text:"Start compressor 173-C-1101A/B per SOP (Refer NHGU SOP Manual)"},
   ]},

   {ctrl:2, title:"Reactor Heating Sequence", steps:[
     {n:23, grp:"STEP 1&2", by:"DCS", type:"signoff", text:"Press START SEQ — GREEN. Confirm SEQ HEALTHYNESS GREEN"},
     {n:24, grp:"STEP 1&2", by:"DCS", type:"check", text:"Sequence checks healthiness of FI2001A/B/C ≥ 1350 Nm³/hr"},
     {n:25, grp:"STEP 1&2", by:"DCS", type:"check", text:"C-1101A or B compressor running feedback checked by logic"},
     {n:26, grp:"STEP 1&2", by:"DCS/Field", type:"field", text:"Furnace light-up done by operator"},
     {n:27, grp:"STEP 1&2", by:"DCS", type:"signoff", text:"F-1101 light-up CONFIRMATION given to proceed further"},
     {n:28, grp:"STEP 1&2", by:"DCS", type:"check", text:"Check healthiness of FALL2001, IS-01, IS-08, PALL5908, PALL5905, PAHH5905"},
     {n:29, grp:"STEP 1&2", by:"DCS", type:"signoff", text:"Press REACTOR HEATING confirmation button"},
     {n:30, grp:"STEP 3", by:"DCS", type:"check", text:"173PIC5903→CAS mode; TIC2209→AUTO mode per logic"},
     {n:31, grp:"STEP 3", by:"DCS", type:"ramp", text:"TIC2209 ramping: 23 °C/hr up to 183 °C from last PV",
      tag:"TIC2209", from:55, target:183, rate:23, rateUnit:"°C/hr"},
     {n:32, grp:"STEP 3", by:"DCS", type:"check", text:"Ramping stops after TIC2209 > 183 °C — sequence completed"},
   ]},

   {ctrl:3, title:"Readiness of Feed & Stripper Circuit", steps:[
     {n:33, grp:"STEP 1", by:"DCS", type:"signoff", text:"Press START SEQ — GREEN. Confirm SEQ HEALTHYNESS GREEN"},
     {n:34, grp:"STEP 1", by:"DCS/Field", type:"field", text:"PDS offsite pump P-1017A/B running on spillback, lined up to NHGU B/L"},
     {n:35, grp:"STEP 1", by:"Field", type:"field", text:"Feed circuit lined from B/L to D-1101"},
     {n:36, grp:"STEP 1", by:"Field", type:"field", text:"N₂ to D-1104 de-blinded; pressurize stripper up to 5.5 kg/cm²g"},
     {n:37, grp:"STEP 1", by:"Field", type:"field", text:"Start-up line to stripper de-blinded; fill stripper above 79%"},
     {n:38, grp:"STEP 1", by:"Field", type:"field", text:"Stripper reboiler steam FIC3001 lined up; condensate system ready"},
     {n:39, grp:"STEP 1", by:"DCS", type:"signoff", text:"Press FEED & STRIPPER CHECK button to proceed"},
     {n:40, grp:"STEP 1", by:"DCS", type:"ramp", text:"173PIC1802A ramps 30 min from last PV → AUTO SP 3 kg/cm²g",
      tag:"PIC1802A", from:0.9, target:3, rate:0.1, rateUnit:"kg/min"},
     {n:41, grp:"STEP 1", by:"DCS", type:"check", text:"173PIC1802B → AUTO with SP 3.2 kg/cm²g"},
     {n:42, grp:"STEP 2", by:"DCS", type:"check", text:"Sequence resets IS-02 and checks IS-02 healthy"},
     {n:43, grp:"STEP 2", by:"DCS", type:"check", text:"Check UV-1601 open feedback by logic"},
     {n:44, grp:"STEP 3", by:"DCS", type:"check", text:"173FIC1601→CAS; LIC1803→AUTO by logic"},
     {n:45, grp:"STEP 3", by:"DCS", type:"ramp", text:"LIC1803 ramps 1.1%/min up to 84% level",
      tag:"LIC1803", from:0, target:84, rate:1.1, rateUnit:"%/min"},
     {n:46, grp:"STEP 4", by:"DCS", type:"check", text:"PHIC2907A→MAN 0% OP; PHIC2907B→CAS mode"},
     {n:47, grp:"STEP 5", by:"DCS", type:"ramp", text:"PIC2907 ramps up to 5.5 kg/cm²g from last PV in 30 min",
      tag:"PIC2907", from:0.9, target:5.5, rate:0.2, rateUnit:"kg/min"},
     {n:48, grp:"STEP 5", by:"DCS", type:"branch", text:"Check LIC2903 ≥ 79%; operator confirmation to proceed",
      tag:"LIC2903", cond:">70"},
     {n:49, grp:"STEP 5", by:"DCS", type:"check", text:"Check 173PIC2907 ≥ 5.5 kg/cm²g"},
     {n:50, grp:"STEP 6&7&8", by:"DCS", type:"check", text:"Check IS-13 interlock healthy; UV-3001 open feedback"},
     {n:51, grp:"STEP 6&7&8", by:"DCS", type:"check", text:"173FIC3001→AUTO SP=0; LIC3001→AUTO SP=50"},
     {n:52, grp:"STEP 6&7&8", by:"DCS", type:"ramp", text:"FIC3001 ramps 57 kg/hr up to 915 kg/hr SP",
      tag:"FIC3001", from:0, target:915, rate:57, rateUnit:"kg/hr"},
     {n:53, grp:"STEP 9&10&11", by:"DCS", type:"check", text:"Check IS-16 and IS-45 healthy; LIC3201 ≥ 34%; MOV3203 open feedback"},
     {n:54, grp:"STEP 9&10&11", by:"DCS/Field", type:"field", text:"Start P-1102A/B by operator; confirmation to proceed"},
     {n:55, grp:"STEP 9&10&11", by:"DCS", type:"check", text:"LIC3201→AUTO SP 51%"},
     {n:56, grp:"STEP 12", by:"DCS", type:"ramp", text:"173PIC2907 ramps up to 9.1 kg/cm²g from last PV in 30 min; stop at SP 10",
      tag:"PIC2907", from:5.5, target:9.1, rate:0.1, rateUnit:"kg/min"},
   ]},

   {ctrl:4, title:"Start Feed Cut-in & Stabilization", steps:[
     {n:57, grp:"STEP 1", by:"DCS", type:"signoff", text:"Press START SEQ — GREEN. Confirm SEQ HEALTHYNESS GREEN"},
     {n:58, grp:"STEP 1", by:"Field", type:"field", text:"Line up feed pump and its spillback FIC1901 by operator"},
     {n:59, grp:"STEP 1", by:"Field", type:"field", text:"Line up HP to LP loop"},
     {n:60, grp:"STEP 1", by:"DCS", type:"signoff", text:"Press FEED CUT-IN & STABILIZATION button to start"},
     {n:61, grp:"STEP 1", by:"DCS", type:"check", text:"Sequence checks FI2001A/B/C ≥ 2610 Nm³/hr by logic"},
     {n:62, grp:"STEP 1", by:"DCS", type:"check", text:"Sequence checks all bed temperatures of R-1101 are < 202 °C"},
     {n:63, grp:"STEP 2", by:"DCS", type:"check", text:"FIC1901→AUTO SP 25 Sm³/hr"},
     {n:64, grp:"STEP 2", by:"DCS", type:"check", text:"Sequence checks IS-01 and IS-02 healthy"},
     {n:65, grp:"STEP 2", by:"Field", type:"field", text:"Start P-1101A/B pump by operator"},
     {n:66, grp:"STEP 2", by:"DCS", type:"signoff", text:"Confirmation to proceed further"},
     {n:67, grp:"STEP 3&4&5", by:"DCS", type:"check", text:"Check IS-03 healthy; confirm UV-1903 opened"},
     {n:68, grp:"STEP 3&4&5", by:"DCS", type:"ramp", text:"FIC1903 ramps 0 → 16 Sm³/hr in 2 min",
      tag:"FIC1903", from:0, target:16, rate:8, rateUnit:"Sm³/min"},
     {n:69, grp:"STEP 3&4&5", by:"DCS", type:"check", text:"Check LIC2501 ≥ 45%; IS-11 healthy; UV2501 opened"},
     {n:70, grp:"STEP 6&7", by:"DCS", type:"check", text:"LIC2501→AUTO SP 51%; FIC2501→CAS mode"},
     {n:71, grp:"STEP 6&7", by:"DCS", type:"check", text:"Check LIC2903 ≥ 90%; IS-14 healthy"},
     {n:72, grp:"STEP 8&9", by:"DCS", type:"check", text:"LIC2903→AUTO SP 90%; LHIC2903A→MAN 0% OP; LHIC2903B→CAS; BALL2201 healthy"},
     {n:73, grp:"STEP 8&9", by:"DCS", type:"ramp", text:"TIC2209 ramps 23 °C/hr up to 238 °C; stop once 238 °C achieved",
      tag:"TIC2209", from:183, target:238, rate:23, rateUnit:"°C/hr"},
   ]},

   {ctrl:5, title:"Start Wash-Water System", steps:[
     {n:74, grp:"STEP 1", by:"DCS", type:"signoff", text:"Press START SEQ — GREEN. Confirm SEQ HEALTHYNESS GREEN"},
     {n:75, grp:"STEP 1", by:"Field", type:"field", text:"Line up wash-water circuit to E-1101A/B"},
     {n:76, grp:"STEP 1", by:"Field", type:"field", text:"Line up DM/stripped water from B/L to D-1108"},
     {n:77, grp:"STEP 1", by:"Field", type:"field", text:"Line up D-1102 sour water to E-1106A/B/C/D; sour water from D-1104 to DHT/DHDS at B/L"},
     {n:78, grp:"STEP 1", by:"DCS", type:"signoff", text:"Press WASH WATER SEQUENCE confirmation button"},
     {n:79, grp:"STEP 1", by:"DCS", type:"check", text:"Check IS-15 healthy; UV-6002 opened"},
     {n:80, grp:"STEP 2-5", by:"DCS", type:"ramp", text:"LIC6001 ramps 1.1%/min up to 70% level",
      tag:"LIC6001", from:0, target:70, rate:1.1, rateUnit:"%/min"},
     {n:81, grp:"STEP 2-5", by:"DCS", type:"check", text:"Check IS-12 healthy; LIC2505→AUTO SP 45%; PIC6002A/B→CAS SP 3 / 3 kg/cm²g"},
     {n:82, grp:"STEP 2-5", by:"DCS", type:"check", text:"Check IS-10 healthy; IS-17A/B healthy; LI6003A/B/C ≥ 56%; PI6010 ≥ 2.6 kg/cm²g"},
     {n:83, grp:"STEP 6&7", by:"DCS", type:"check", text:"HS6001 reset by logic; check UV6001 opened; FIC6002→AUTO SP=0; FIC6004→AUTO SP 4 Sm³/hr"},
     {n:84, grp:"STEP 6&7", by:"DCS/Field", type:"field", text:"Start P-1103A/B by operator; confirmation after starting"},
     {n:85, grp:"STEP 6&7", by:"DCS", type:"ramp", text:"FIC6002 ramps up to 1.1 Sm³/hr in 1 min; stop at SP 1 — SEQUENCE COMPLETED",
      tag:"FIC6002", from:0, target:1.1, rate:1.1, rateUnit:"Sm³/min"},
   ]},
  ],

  // ---- EMERGENCY HANDLING — transcribed from the LOUP SOP Book (6000-series) ----
  // Each scenario is a real SOP staying-action procedure. Tags/values as written.
  // ESD bed-trip thresholds throughout: R-01/R-02/R-03 = 367/324/229 °C.
  EMERGENCIES: {
   h2: {code:"6001", title:"Complete Hydrogen Failure", note:"Make-up H₂ lost (supply-side or 99-C-01 trip). Staying action on ILR; de-oil if outage long.", controllers:[
     {ctrl:1, title:"Complete Hydrogen Failure — Course of Action", steps:[
      {n:1, grp:"COURSE OF ACTION", by:"DCS/Field", type:"field", text:"Immediately place unit on Internal Liquid Recirculation (ILR) per procedure; close Purge Gas line if open"},
      {n:2, grp:"COURSE OF ACTION", by:"DCS", type:"field", text:"Inform DAK board man to initiate DAK shutdown due to H₂ failure"},
      {n:3, grp:"COURSE OF ACTION", by:"DCS/Field", type:"check", text:"Bypass suction-pressure trip of 99-C-02A/B (107.4 kg/cm²) — keep RGC ON to sweep oil from reactors"},
      {n:4, grp:"COURSE OF ACTION", by:"DCS", type:"ramp", text:"Reduce 99-F-01/02 firing — bring HDT & MSDW/HDF inlets ~41 °C below outage temp (cuts H₂ use)",
       tag:"HDT_ART", from:330, target:289, rate:23, rateUnit:"°C/hr"},
      {n:5, grp:"COURSE OF ACTION", by:"DCS", type:"check", text:"If H₂ unavailable > 48 hr, consult planner & section head before de-oiling"},
      {n:6, grp:"COURSE OF ACTION", by:"DCS", type:"ramp", text:"Gradually lower HDT ART to 183 °C; MSDW/HDF ARTs to 206/155 °C (oil cut-in temp)",
       tag:"HDT_ART", from:289, target:183, rate:23, rateUnit:"°C/hr"},
      {n:7, grp:"COURSE OF ACTION", by:"DCS", type:"check", text:"Increase recycle-gas flow to E-03 to avoid FALL1701/FALL2501 actuation (prevent F-01/02 trip)"},
      {n:8, grp:"DE-OILING", by:"DCS/Field", type:"field", text:"Once ARTs at target: stop ILR, close battery feed, route DWO to off-spec tank TK-1325"},
      {n:9, grp:"DE-OILING", by:"DCS/Field", type:"field", text:"~15 min before stopping feed, bypass product around 99-E-01 exchanger"},
      {n:10, grp:"DE-OILING", by:"DCS/Field", type:"field", text:"Stop feed pumps P-43 and P-02 (start de-oiling R-01/02/03)"},
      {n:11, grp:"DE-OILING", by:"DCS/Field", type:"field", text:"After de-oiling R-01, divert T-01 liquid to D-04 (avoid oil to R-02/03)"},
      {n:12, grp:"DE-OILING", by:"DCS/Field", type:"field", text:"Stop P-10 and P-11 after de-oiling R-01 (do not run P-10 at low system pressure)"},
      {n:13, grp:"DE-OILING", by:"DCS/Field", type:"check", text:"Max gas circulation; hold reactor temps until T-01 & D-04 level rise < 1.1%/hr (2–3 hr). Then bottle up (stop C-01/02) or shut down under N₂ — COMPLETE"},
     ]}]},

   rgc: {code:"6002", title:"Recycle Gas Compressor (99-C-02) Failure", note:"RGC tripped, restart unlikely <10 min. Treat & quench gas lost — TRIP FURNACES ASAP, do not wait for restart.", controllers:[
     {ctrl:1, title:"RGC 99-C-02A/B Failure", steps:[
      {n:1, grp:"IMMEDIATE", by:"DCS", type:"signoff", text:"Verify interlock has shut down 99-F-01/02 furnaces; if not, manually activate interlock / reduce firing. Liquid feed to HDT stops after 10 min"},
      {n:2, grp:"IMMEDIATE", by:"Field", type:"field", text:"Isolate main burner isolation valves of furnaces; isolate pilot gas burners if tripped"},
      {n:3, grp:"IMMEDIATE", by:"DCS", type:"check", text:"Open D-06 to flare (99FC3202 & 99PC3203) — purge H₂ to flare, hold pressure, maintain H₂ across reactors"},
      {n:4, grp:"IMMEDIATE", by:"DCS", type:"check", text:"Increase Make-Up Gas to max; divert around 99-T-01 via FC2106 bypass to cool MSDW/HDF reactors"},
      {n:5, grp:"IMMEDIATE", by:"Field/DCS", type:"field", text:"Restart same or standby RGC per procedure"},
      {n:6, grp:"IF NOT RESTARTED", by:"DCS", type:"check", text:"Fresh feed flows 10 min after outage; if RGC not restarted in 10 min, 99-P-02 charge pump trips (interlock)"},
      {n:7, grp:"IF NOT RESTARTED", by:"DCS/Field", type:"field", text:"Bypass R-02/03 — divert T-01 bottom to D-04 (prevent liquid accumulation)"},
      {n:8, grp:"IF NOT RESTARTED", by:"Field", type:"field", text:"Open E-06 tube-side bypass (prevent liquid accumulation at R-02 bottom & exotherm)"},
      {n:9, grp:"IF NOT RESTARTED", by:"Field", type:"field", text:"Divert DWO and HD to off-spec"},
      {n:10, grp:"IF NOT RESTARTED", by:"Field", type:"field", text:"Start short loop to keep F-03 running; if F-03 trips, isolate tripped gas burners"},
      {n:11, grp:"MONITOR", by:"DCS", type:"check", text:"Continuously monitor reactor ARTs & bed profiles (esp. HDT) for exotherm after feed stops"},
      {n:12, grp:"MONITOR", by:"DCS", type:"signoff", text:"⚠ If any bed HDT/MSDW/HDF exceeds 367/324/229 °C → PRESS ESD, depressure (110 psi/min then 220 psi/min) to control exotherm"},
      {n:13, grp:"RECOVERY", by:"DCS/Field", type:"check", text:"If depressured, determine RGC restart vs extended shutdown"},
      {n:14, grp:"RECOVERY", by:"DCS/Field", type:"field", text:"If extended, proceed Shutdown under Nitrogen per manual (avoid H₂ — may reactivate exotherm)"},
      {n:15, grp:"RECOVERY", by:"DCS/Field", type:"check", text:"If RGC restartable, slowly re-pressurize with make-up H₂; restart RGC; stabilize ARTs 205–197 °C (HDT), 183/155 °C (MSDW/HDF) — COMPLETE"},
     ]}]},

   ia: {code:"6003", title:"Instrument Air Failure", note:"All valves go fail-safe: liquid FCs close, gas FCs open, fuel FCs close; furnace trips; chopper valves isolate HP from LP.", controllers:[
     {ctrl:1, title:"Instrument Air Failure", steps:[
      {n:1, grp:"PROCEDURE", by:"DCS/Field", type:"check", text:"IA failure → liquid FCs fail-close, gas FCs fail-open, fuel FCs fail-close; furnace shuts; chopper valves at 99-T-01/D-02/D-04/D-05 close. If long-term, shut down under N₂"},
      {n:2, grp:"PROCEDURE", by:"DCS/Field", type:"field", text:"Monitor all reactor temperature profiles; if exothermic, open depressurizing XVs to induce gas flow & cool catalyst; use bypasses to manually control levels"},
      {n:3, grp:"PROCEDURE", by:"DCS", type:"check", text:"If IA restorable soon (under H₂) & temps stable ≤248 °C HDT / 41 °C below outage MSDW-HDF: close backpressure FV-3202 & depressurizing XVs to hold pressure → go to step 6; else continue"},
      {n:4, grp:"PROCEDURE", by:"DCS", type:"check", text:"Continue monitoring as pressure lowers; if system P < N₂ supply, start N₂ (once-through) to increase gas flow over catalyst"},
      {n:5, grp:"PROCEDURE", by:"DCS/Field", type:"field", text:"If N₂ introduced and IA failure continues, take Shutdown Under Nitrogen"},
      {n:6, grp:"PROCEDURE", by:"DCS/Field", type:"check", text:"After IA restored, restart unit with 'Dry' catalyst — COMPLETE"},
     ]}]},

   feedpump: {code:"6004", title:"Offsite Feed Pump P-01 Failure", note:"Raffinate feed from OSBL P-01 lost. P-32A/B (flushing oil pumps) available as backup feed.", controllers:[
     {ctrl:1, title:"Offsite Feed Pump P-01A/B Failure", steps:[
      {n:1, grp:"IMMEDIATE", by:"DCS/Field", type:"field", text:"Immediately place unit on ILR; open ILR valves; isolate battery-limit feed & product; fully open FC1201 for circulation"},
      {n:2, grp:"BACKUP FEED", by:"DCS", type:"check", text:"Coordinate with LR OM&S; changeover distillate to raffinate for P-32A/B (maintain feed)"},
      {n:3, grp:"BACKUP FEED", by:"DCS", type:"check", text:"P-32A/B can feed surge drum via LV1205 (selection switch for surge-drum level)"},
      {n:4, grp:"IF COMPLETE FAILURE", by:"DCS", type:"check", text:"Maintain operating ARTs for 4 hr (depends on oil inventory in circulation)"},
      {n:5, grp:"IF COMPLETE FAILURE", by:"DCS", type:"ramp", text:"Gradually lower HDT ART 20–23 °C and MSDW/HDF ARTs 15–18 °C below last; hold 16–24 hr",
       tag:"HDT_ART", from:330, target:309, rate:23, rateUnit:"°C/hr"},
      {n:6, grp:"IF COMPLETE FAILURE", by:"DCS", type:"check", text:"If feed unavailable long, reduce unit circulation to min 40 m³/hr"},
      {n:7, grp:"IF COMPLETE FAILURE", by:"DCS", type:"ramp", text:"Gradually lower HDT ART to 248 °C; MSDW/HDF ARTs 41 °C below last; hold 24 hr",
       tag:"HDT_ART", from:309, target:248, rate:23, rateUnit:"°C/hr"},
      {n:8, grp:"IF COMPLETE FAILURE", by:"DCS/Field", type:"check", text:"Keep recovery section in hot circulation; follow ILR to avoid oil-inventory loss"},
      {n:9, grp:"IF COMPLETE FAILURE", by:"DCS", type:"check", text:"At these temps under ILR + hot H₂, unit can idle indefinitely — decide restart when feed available — COMPLETE"},
     ]}]},

   liquidcharge: {code:"6005", title:"Loss of Onsite Liquid Charge (P-02 / P-43)", note:"Onsite feed charge pump P-02 or booster P-43 lost — NO ILR possible; shut down.", controllers:[
     {ctrl:1, title:"Loss of Onsite Liquid Charge", steps:[
      {n:1, grp:"COURSE OF ACTION", by:"DCS/Field", type:"field", text:"Reduce furnace firing manually; maximize treat-gas flow to reactors (minimize temp spike from mass-flow loss)"},
      {n:2, grp:"COURSE OF ACTION", by:"DCS", type:"ramp", text:"Reduce R-01 (HDT) ART to 248 °C using quench at < 23 °C/hr (prevent catalyst desulphiding)",
       tag:"HDT_ART", from:330, target:248, rate:23, rateUnit:"°C/hr"},
      {n:3, grp:"COURSE OF ACTION", by:"DCS", type:"ramp", text:"Reduce R-02/R-03 (MSDW/HDF) ART 41 °C below last (cool concurrently with HDT)",
       tag:"MSDW_ART", from:312, target:271, rate:23, rateUnit:"°C/hr"},
      {n:4, grp:"HOLD / RESTART", by:"DCS", type:"check", text:"If repairs within 24 hr → restart 'Start-up with Wet Catalyst'"},
      {n:5, grp:"HOLD / RESTART", by:"DCS", type:"ramp", text:"If not within 24 hr, reduce ARTs: R1→183 °C, R2→206 °C, R3→160 °C",
       tag:"HDT_ART", from:248, target:183, rate:23, rateUnit:"°C/hr"},
      {n:6, grp:"HOLD / RESTART", by:"DCS", type:"check", text:"If repairs in second 24-hr hold → restart 'Start-up with Wet Catalyst'"},
      {n:7, grp:"HOLD / RESTART", by:"DCS/Field", type:"field", text:"If extended, proceed Shutdown under Nitrogen per manual (protect R-01 HDT activity) — COMPLETE"},
     ]}]},

   dwo: {code:"6006", title:"Dewaxed Oil Pump 99-P-05 Failure", note:"Dewaxed base-oil product pump cavitation/trip — risk of 99-T-06/T-05 overflow.", controllers:[
     {ctrl:1, title:"Dewaxed Oil Pump 99-P-05A/B Failure", steps:[
      {n:1, grp:"A · STANDBY AVAILABLE", by:"DCS", type:"check", text:"Check P-05 discharge flow (99FC3702, 99FC4101) & T-06 level to confirm P-05 not giving flow (cavitation → recycle opens to 112%, T-06 rises)"},
      {n:2, grp:"A · STANDBY AVAILABLE", by:"DCS", type:"check", text:"Check P-05 run indication; if tripped, inform shift electrical to reset in substation"},
      {n:3, grp:"A · STANDBY AVAILABLE", by:"Field", type:"field", text:"Inform field crew to check pump discharge pressure & amps (confirm cavitation) — do NOT delay (T-06/T-05 overflow risk)"},
      {n:4, grp:"A · STANDBY AVAILABLE", by:"DCS", type:"field", text:"Check DWO battery-limit pressure; if high (blockage) inform OM&S; if delayed, divert DWO to off-spec & normalize flow"},
      {n:5, grp:"A · STANDBY AVAILABLE", by:"DCS", type:"check", text:"Confirm product routing not blocked; route DWO back to product tankage from off-spec"},
      {n:6, grp:"A · STANDBY AVAILABLE", by:"DCS", type:"field", text:"Close then slowly open FC4101 & 99FC3702 to pick the pump up (don't keep closed long)"},
      {n:7, grp:"A · STANDBY AVAILABLE", by:"DCS", type:"check", text:"Check P-07 flow to E-14 (if diverted in SPO/ILR) and reduce; ensure T-07/T-08 levels controlled"},
      {n:8, grp:"A · STANDBY AVAILABLE", by:"Field", type:"field", text:"Check P-05 discharge pressure & amps in field (normal 15–18.2 kg/cm²) to confirm cavitation"},
      {n:9, grp:"A · STANDBY AVAILABLE", by:"DCS", type:"check", text:"If pressure/amps normal, take FC3702 to manual, close & check flow in FC4101 (normalizes product flow)"},
      {n:10, grp:"A · STANDBY AVAILABLE", by:"Field", type:"field", text:"If cavitated, close discharge valve to build pressure, open slowly & normalize"},
      {n:11, grp:"A · STANDBY AVAILABLE", by:"Field", type:"field", text:"If pump not picking up on 1st attempt, start standby P-05 & stop the earlier pump"},
      {n:12, grp:"A · STANDBY AVAILABLE", by:"Field", type:"field", text:"After stabilizing, find cause; hand over pump to maintenance (strainer cleaning etc.)"},
      {n:13, grp:"B · NO STANDBY", by:"DCS", type:"check", text:"Reduce feed to 34 m³/hr; increase T-05 pressure to 242 mmHg; keep trying to pick up pump (raises P-05 head)"},
      {n:14, grp:"B · NO STANDBY", by:"DCS", type:"check", text:"Increase F-03 COT +9 °C; raise T-05 top temp to 188 °C; maximize HD pull; raise T-04 top temp (lift heavier liquids, avoid overflow)"},
      {n:15, grp:"B · NO STANDBY", by:"Field", type:"field", text:"If pump not normal > 15 min, inform plant manager & start de-oiling LOUP per procedure"},
      {n:16, grp:"B · NO STANDBY", by:"DCS", type:"check", text:"Raise T-01/D-04/T-04 levels to 90%; bypass E-01A/B shell side while de-oiling — COMPLETE"},
     ]}]},

   amine: {code:"6007", title:"HP Amine Pump P-11 Failure", note:"Lean amine to HP absorber T-02 lost. Fresh feed makes H₂S → poisons R-02; go ILR on pure recycle gas.", controllers:[
     {ctrl:1, title:"HP Amine Pump P-11A/B Failure", steps:[
      {n:1, grp:"COURSE OF ACTION", by:"DCS/Field", type:"field", text:"Stop distillate punching; place unit on ILR. Isolate battery-limit feed/product; fully open FC1201; reduce circulation to min 40 m³/hr (H₂S poisons R-02)"},
      {n:2, grp:"COURSE OF ACTION", by:"DCS", type:"check", text:"Maximize purging recycle gas to flare via PV-3203 (maintain recycle-gas purity)"},
      {n:3, grp:"COURSE OF ACTION", by:"DCS", type:"check", text:"Maximize make-up H₂ to R-02 via FV2106 (T-01 bypass) — high-purity gas to avoid catalyst poisoning"},
      {n:4, grp:"COURSE OF ACTION", by:"DCS", type:"ramp", text:"Reduce 99-F-01/02 firing — HDT & MSDW/HDF inlets ~41 °C below last; reduce F-03 COT to 183 °C",
       tag:"HDT_ART", from:330, target:289, rate:23, rateUnit:"°C/hr"},
      {n:5, grp:"COURSE OF ACTION", by:"DCS", type:"ramp", text:"Gradually lower HDT ART to 183 °C; MSDW/HDF ARTs to 206/155 °C (oil cut-in)",
       tag:"HDT_ART", from:289, target:183, rate:23, rateUnit:"°C/hr"},
      {n:6, grp:"RECOVERY SECTION", by:"Field", type:"field", text:"Stop P-07A/B; isolate HD product valves at B/L (or keep running via E-14 outlet FV3804)"},
      {n:7, grp:"RECOVERY SECTION", by:"DCS/Field", type:"field", text:"Stop stripping steam to T-07 (FC3801); isolate block valves (avoid steam condensation)"},
      {n:8, grp:"RECOVERY SECTION", by:"DCS", type:"check", text:"Maintain recycle gas (FI1701A/B/C) & treat gas (FI2501A/B/C) flows to avoid furnace trip"},
      {n:9, grp:"RECOVERY SECTION", by:"DCS", type:"check", text:"Maintain system pressure via fresh H₂ make-up from C-01A/B; keep C-02 ON for oil sweeping"},
      {n:10, grp:"DE-OILING", by:"DCS/Field", type:"field", text:"Divert T-01 bottom to D-04; de-oil R-02/03"},
      {n:11, grp:"DE-OILING", by:"DCS", type:"check", text:"Reduce top temp of T-04 & T-05 to maintain oil levels (sustain circulation)"},
      {n:12, grp:"DE-OILING", by:"DCS/Field", type:"field", text:"Shut steam to T-05 & ejectors J-01/02; break vacuum (isolate steam to J-03/04/05); keep min steam to T-04"},
      {n:13, grp:"DE-OILING", by:"Field", type:"field", text:"Watch T-05 draw-off tray level (LC3708); stop pump P-06A/B (avoid cavitation)"},
      {n:14, grp:"DE-OILING", by:"DCS", type:"check", text:"Unit can stay in ILR indefinitely — oil in R-01 (ART 183 °C), pure recycle in R-02/03 (206/155 °C); ready when amine available — COMPLETE"},
     ]}]},

   scw: {code:"6008", title:"Sea Cooling Water Failure", note:"SCW lost → MGC 99-C-01 trips ~15 min, RGC 99-C-02 ~1 hr; T-05 vacuum breaks. Go ILR, de-oil, watch for exotherm.", controllers:[
     {ctrl:1, title:"Sea Cooling Water Failure", steps:[
      {n:1, grp:"IMMEDIATE", by:"DCS/Field", type:"field", text:"Inform LR OM&S supervisor (land phone/radio) to normalize tripped/cavitated pump or start standby"},
      {n:2, grp:"IMMEDIATE", by:"Field", type:"field", text:"Start back-flushing MUG/RGC exchangers and E-36/E-18 (use SCW return-header pressure to prevent RGC/MGC trip)"},
      {n:3, grp:"IMMEDIATE", by:"DCS/Field", type:"field", text:"If SCW unavailable long, take LOUP on ILR (hold system pressure before MGC trips)"},
      {n:4, grp:"IMMEDIATE", by:"Field", type:"field", text:"Start draining water in JCW tank (C-01/02) Tk-2/Tk-3 (keep JCW temp in control)"},
      {n:5, grp:"STABILIZE", by:"DCS", type:"check", text:"Reduce steam to ejectors if T-05 pressure high (adjust 99PC4002)"},
      {n:6, grp:"STABILIZE", by:"DCS", type:"check", text:"Reduce top temp of 99-T-04 & 99-T-05 to maintain vessel levels (maintain circulation)"},
      {n:7, grp:"COOL & DE-OIL", by:"DCS/Field", type:"ramp", text:"Reduce ART of 99-R-01 & 99-R-02 by reducing 99-F-01/02 firing (normal shutdown)",
       tag:"HDT_ART", from:330, target:275, rate:23, rateUnit:"°C/hr"},
      {n:8, grp:"COOL & DE-OIL", by:"DCS/Field", type:"field", text:"Start de-oiling 99-R-02 (ART < 275 °C) — divert T-01 bottom to 99-D-04; isolate oil inlet to E-02 (after 10 min of 99-C-01 trip if SCW out > 1 hr)"},
      {n:9, grp:"COOL & DE-OIL", by:"DCS/Field", type:"check", text:"Maintain DP between R-02 inlet & D-04 inlet > 1.8 kg/cm²g by increasing purge from 99-D-06 (aids de-oiling R-02/03)"},
      {n:10, grp:"COOL & DE-OIL", by:"DCS/Field", type:"field", text:"Shut stripping steam to 99-T-04 (FC3301), 99-T-05 (FC3701) & ejector 99-J-01 before temp < 183 °C; isolate lines"},
      {n:11, grp:"MONITOR", by:"DCS", type:"check", text:"Watch gas-valve temp & lube-oil temps of both MGC & RGC"},
      {n:12, grp:"MONITOR", by:"DCS/Field", type:"check", text:"Monitor T-03 overhead temp; if needed start water sprinkler on AFC-01A/B (prevent water carryover to R-02)"},
      {n:13, grp:"MONITOR", by:"DCS/Field", type:"ramp", text:"Increase gas circulation in 99-R-01 (via quench) to cool; bring R1 to 206 °C; start de-oiling; stop feed pump 99-P-02",
       tag:"HDT_ART", from:275, target:206, rate:23, rateUnit:"°C/hr"},
      {n:14, grp:"MONITOR", by:"DCS/Field", type:"field", text:"If 99-C-02 trips, start standby RGC (keep trip interlock FALL1701A/B/C & FALL2501A/B/C in line)"},
      {n:15, grp:"EXOTHERM", by:"DCS", type:"signoff", text:"⚠ Watch all reactor bed outlet temps; if abnormal increase, operate emergency depressurization @ 110 psi"},
      {n:16, grp:"EXOTHERM", by:"DCS", type:"signoff", text:"⚠ If temp rise continues, operate emergency depressurization @ 100+220 psi; reduce LOUP system pressure to 4.5 kg/cm² — COMPLETE"},
     ]}]},

   runaway: {code:"6009", title:"Reactor Temperature Runaway — Restart after ESD", note:"After a runaway/ESD: cool with N₂ below 229 °C, N₂-purge to spec, then controlled re-pressurization and H₂ intro. ESD thresholds 367/324/229 °C (R-01/02/03).", controllers:[
     {ctrl:1, title:"Restart after Temperature-Runaway Depressurization", steps:[
      {n:1, grp:"COOL WITH N₂", by:"DCS/Field", type:"check", text:"Initial condition: after ESD, all H₂ purged to flare; system below 4.5 kg/cm²"},
      {n:2, grp:"COOL WITH N₂", by:"DCS/Field", type:"field", text:"De-blind N₂ at C-02 discharge and C-01A/B suction; inform utility; keep torqueing crew ready (ESD may cause flange leaks)"},
      {n:3, grp:"COOL WITH N₂", by:"DCS/Field", type:"ramp", text:"Introduce N₂ via C-02 discharge & quench to exotherm bed; keep flaring from D-06; bring all bed TIs below 229 °C uniformly",
       tag:"BED_Tmax", from:275, target:225, rate:9, rateUnit:"°C/min"},
      {n:4, grp:"COOL WITH N₂", by:"DCS/Field", type:"branch", text:"Purge with N₂ until uniform profile < 229 °C across R-01/02/03. If any bed ≥ 250 → maintain quench / HOLD",
       tag:"BED_Tmax", cond:"<229"},
      {n:5, grp:"N₂ PURGE TO SPEC", by:"DCS/Field", type:"check", text:"After uniform profile, proceed to pressurization/depressurization cycles"},
      {n:6, grp:"N₂ PURGE TO SPEC", by:"DCS/Field", type:"ramp", text:"Pressurize HP circuit to 4.5 kg/cm² from N₂ (do not exceed 6.4 kg/cm² with N₂ per catalyst vendor)",
       tag:"SYS_P", from:0.5, target:4.5, rate:0.9, rateUnit:"kg/min"},
      {n:7, grp:"N₂ PURGE TO SPEC", by:"DCS/Field", type:"field", text:"Introduce N₂ via D-07A/B & to C-02 discharge; ensure C-02 bypass closed; keep bladder for gas sampling"},
      {n:8, grp:"N₂ PURGE TO SPEC", by:"DCS/Field", type:"ramp", text:"Depressurize HP circuit to flare via D-06 & D-02 PSV bypass",
       tag:"SYS_P", from:4.5, target:0.5, rate:0.9, rateUnit:"kg/min"},
      {n:9, grp:"N₂ PURGE TO SPEC", by:"DCS/Field", type:"check", text:"Repeat pressurize/depressurize thrice; sample N₂ at D-06 GC: O₂ < 0.8%, dew point −37 °C (two consecutive); repeat if off-spec"},
      {n:10, grp:"H₂ INTRODUCTION", by:"DCS/Field", type:"field", text:"If spec met, depressurize D-06 to flare; reduce HP section to 0.5 kg/cm²; prepare slow H₂ intro (⚠ if exotherm & bed hits 367/324/229 °C, PRESS ESD)"},
      {n:11, grp:"H₂ INTRODUCTION", by:"DCS/Field", type:"field", text:"Inform HGU for H₂ @ 2700 Nm³/hr; verify N₂ blinds & temp connections removed; take H₂ to PV1381, flare 1 hr, check dew −37 °C, H₂ 112%, CO+CO₂ 9 ppm"},
      {n:12, grp:"H₂ INTRODUCTION", by:"DCS/Field", type:"check", text:"If specs not met, repeat; once achieved, prepare unit for N₂ freeing"},
      {n:13, grp:"RE-PRESSURIZE", by:"DCS/Field", type:"ramp", text:"Pressurize unit to 9.1 kg/cm²g via H₂ through C-01A/B (circuit lined up, C-02 start-up bypass open) @ 11 kg/hr",
       tag:"SYS_P", from:0.5, target:9.1, rate:9.1, rateUnit:"kg/hr"},
      {n:14, grp:"RE-PRESSURIZE", by:"DCS/Field", type:"field", text:"Stop pressurization; close C-02 bypass; depressurize via HS3103 & HS3104 on HWC; record time"},
      {n:15, grp:"RE-PRESSURIZE", by:"DCS/Field", type:"ramp", text:"Re-pressurize with H₂ to 18.2 kg/cm²g; leak-test with soap; attend leaks; if none, start 99-C-01A/B per SOP",
       tag:"SYS_P", from:9.1, target:18.2, rate:9.1, rateUnit:"kg/hr"},
      {n:16, grp:"RESTART", by:"DCS/Field", type:"field", text:"Ask instrument to take GC in service at D-06 overhead"},
      {n:17, grp:"RESTART", by:"DCS/Field", type:"check", text:"If MPT (min pressurization temp) conditions not met, achieve reactor MPT; else proceed"},
      {n:18, grp:"RESTART", by:"DCS/Field", type:"check", text:"Unit start-up per 'Start-up under Hydrogen' procedure — COMPLETE"},
     ]}]},
  },
};
